version: '3'

services:
  postgres:
    container_name: postgres
    image: 'postgres:12.1'
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - '5432'
    volumes:
    - .:/data/www
