version: '3'

services:
  postgres-1:
    container_name: postgres-2
    image: 'postgres:12.1'
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - '5432'
